-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "app_closed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "crowns" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "diamonds" INTEGER NOT NULL DEFAULT 5;
