-- CreateEnum
CREATE TYPE "AchievementConditionTypes" AS ENUM ('PLAY_SOLO_GAMES', 'COMPLETE_SOLO_GAMES', 'COLLECT_COMIC_PIECES', 'FIND_COLLECTABLE_PIECES', 'ANSWERS_CORRECTLY', 'ANSWERS_CORRECTLY_IN_ROW', 'LEVEL_REACH', 'CHALLENGE_MATCHES', 'WIN_CHALLENGE_MATCHES', 'WIN_CHALLENGE_MATCHES_WITHOUT_ITEM_USE', 'COINS_EARN', 'COINS_SPEND', 'MONTHLY_BONUS_CLAIMS', 'ITEMS_USE', 'KAOS_VISIOS_ITEM_USE', 'MICROPHONE_ITEM_USE', 'DO_OVER_ITEM_USE', 'TIME_ZONE_ITEM_USE', 'COMPLETE_CHAPTER_2_OF_STEVE_STORY');

-- CreateEnum
CREATE TYPE "AchievementRewardsTypes" AS ENUM ('TITLE', 'COINS', 'DIAMONDS', 'PROFILE_PICTURE', 'ALL_ITEMS', 'ITEMS_DO_OVER_TIME_ZONE', 'ITEMS_KAOS_VISION_MICROPHONE');

-- CreateTable
CREATE TABLE "AchievementConditions" (
    "id" TEXT NOT NULL,
    "achievement_id" TEXT NOT NULL,
    "condition_type" "AchievementConditionTypes" NOT NULL,
    "condition_qty" INTEGER NOT NULL,
    "reward_type" "AchievementRewardsTypes" NOT NULL,
    "reward_qty" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "AchievementConditions" ADD FOREIGN KEY ("achievement_id") REFERENCES "Achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE;
